// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

error Pool__InvalidTokenAddress();
error Pool__InvalidAssetForDeposit();
error Pool__InvalidUserAddress();
error Pool__WrongAsset();
error Pool__InvalidAPY();
error Pool__InvalidMinPeriod();
error Pool__NoPoolDepositsFound();
error Pool__DepositNotActive();
error Pool__DepositPeriodStillActive();
error Pool__IndexOutOfBounds();
error Pool__PoolInactiveOrNonExistent();
error Pool__InvalidDepositType();
error Pool__PeriodTooShort();
error Pool__InvalidPoolAsset();
error Pool__AlreadyDeposited();
error Pool__InvalidAmount();
error Pool__InvalidValue();
error Pool__SendFailed();
error Pool__GovernanceAlreadySet();
error Pool__InvalidGovernanceAddress();
error Pool__CoverAlreadySet();
error Pool__InvalidCoverAddress();
error Pool__VaultAlreadySet();
error Pool__InvalidVaultAddress();
error Pool__PoolCanisterAlreadySet();
error Pool__InvalidPoolCanisterAddress();
error Pool__NotGovernance();
error Pool__NotCover();
error Pool__NotVault();
error Pool__NotPoolCanister();
